examples/feed-generator/generate.py, examples/feed-generator/settings.py, pymisp/api.py
- also some minor modifications to the get_index api
=> Script for the upcoming feed generator

examples/feed-generator/generate.py
- only save fields that are actually necessary and don't reveal too much of unneeded information (such as correlation)
- add contextual fields to the manifest
=> Updated the feed generator

pymisp/api.py
it's possible to add_tag at an event and to put value 'inherit' to attribute
=> add add_tag method to an event and value 5 to distribution attribute

pymisp/api.py
I add a method to change change a threat level on existent event
=> add method change_threat_level

pymisp/api.py, tests/test.py
Some improvements here and there as I'm using it. Can leave the PR open for a few days until I've finalized some stuff. I'm just going to dump all changes here, as individual PRs for each commit is kind of a hassle.
Please let me know if you some commits need additional work to be acceptable from your side.
=> Various improvements

pymisp/api.py, pymisp/mispevent.py, tests/test_offline.py
Honestly, I did not tested the code in real usage, I limited myself to the unit-tests and caught a few corner cases in other parts of the code.
=> Factorize all add_attributes functions

pymisp/api.py
the uuid need to validate this regex : ('^[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12}\Z', re.I)
=> Add uuid serch with pymisp

examples/addtag.py
guess that way it is easier to understand
=> make it little more readable

pymisp/api.py
This allow all functions to set/update authkey of a user in PyMISP.
=> feature: Add support for authkey in PyMISP operations

pymisp/api.py
Adds four new methods to add and edit servers in MISP:
- add_server to create a new server with parameters
- add_server_json to create a ne server from a json file
- edit_server to edit a server from parameters
- edit_server_json to edit a server from a json file
=> Adds new methods to add and edit servers in MISP

examples/addtag2.py
Made a quick addtag2.py to replace (maybe) the weirdo addtag.py ;)
Only uses the tag() API call (no call to add_tag())
Still a bit messy to tag attributes, but works fine.
=> example using tag() function instead of add_tag()

examples/search.py
Accepts specific parameters from search() instead of just using search_all().
=> Example using the search() function

tests/test.py
- attribute_count default changed to 0 in misp
=> Small change to make travis happy

examples/situational-awareness/README.md
Modification par Yacine Khamis
=> Treemap.py requirements updated in the README.MD file

pymisp/api.py
Add scope to list organisations, as it's done in web Interface.
=> feat: add filter to specify which organisation to list

tests/test.py
These are not really beautiful tests, but it's a start
=> test: add test for user and organisation

pymisp/api.py
Fix issue: https://github.com/CIRCL/PyMISP/issues/78
=> Normalize output between misp.search_index and misp.search

pymisp/tools/openioc.py
Travis correction : https://travis-ci.org/MISP/misp-modules/jobs/231065469
refactoring code
Add composite for RegistryItem/Path|RegistryItem/Text form test ioc
=> correction, refactoring, addition

examples/del.py
=> use misp_verifycert

examples/cache_all.py, pymisp/api.py
Hey there, I made just a few simple changes to allow users to automate caching all feeds using a simple API call.
=> Create cache feeds function in PyMISP

pymisp/api.py
new publish method that is less resourceful and also having the ability to send emails (same as the web interface).
The method depends on the publish misp api method instead of update.
=> Implemented much faster publish method to replace the old one

examples/add_generic_object.py
usage: add_generic_object.py [-h] -e EVENT -t TYPE -d DICT
Examples:
python3 add_generic_object.py -e 1683 -t email -d '{"subject":"The Pink Letter", "to":"jon@snow.org"}'
python3 add_generic_object.py -e 2343 -t person -d '{"first-name":"Daenerys", "last-name":"Targaryen", "place-of-birth":"Dragonstone"}'
python3 add_generic_object.py -e 3596 -t "domain|ip" -d '{"domain":"stormborn.org", "ip":"50.63.202.33"}'
=> Created add_generic_object.py

pymisp/api.py
Regarding #137; adding multiple attributes as a proposal in one request is not possible on MISPs side atm.
=> Adding multiple named attributes (without proposal) require a single POST request now

pymisp/api.py, tests/test_offline.py
Starting to make my offer to contribute measurable - I sighted the issues, but thought enhancing coverage would be the best first way to go. One of the test found an error in the flattening method, the fix may be breaking other usage, but input here should be helpful ;-) 
Hope it helps.
=> First friendly contribution enhance coverage

pymisp/abstract.py, pymisp/mispevent.py, pymisp/tools/create_misp_object.py, pymisp/tools/elfobject.py, pymisp/tools/fileobject.py, pymisp/tools/machoobject.py, pymisp/tools/peobject.py, pymisp/tools/vtreportobject.py
=> chg: Make the library easier to use

pymisp/mispevent.py
- fix MISPObject missing distribution concept
- fix language typo paramaters => parameters
=>  fix MISPObject missing distribution and sharing_group_id

pymisp/mispevent.py
Manage distribution and sharing_group_id as dict key like the other fields.
-- Not sure about default
=> _default_attributes_parameters - if set - is a dict

pymisp/api.py
Maybe I didn't use it correctly but the method set_sightings didn't work for me. It's working now but I'm not sure whether sending a request for every sighting in the list is the best solution.
=> set_sightings

pymisp/api.py
Added function to change comment for attribute by attribute uuid
=> Change the comment of attribute

pymisp/api.py
Now is possible add hidden tags from PyMISP
=> Change in new_tag function. Added attributie 'hide_tag'

examples/add_sbsignature.py, pymisp/tools/__init__.py, pymisp/tools/sbsignatureobject.py
Created sb-signature library with relative example for testing.
Thanks @dadokkio
=> sb-signature library

.travis.yml, pymisp/mispevent.py, tests/test_offline.py
Hi,
This PR add tests for the following items:
- regression tests for #174 
- uploading a sample
- improve regkeys attribute testing
- tag/untag functions in the API
It also add coverage for the tests in order to avoid untested functions inside the tests
Thanks!
=> Add and refactor some tests

examples/feed-generator/settings.default.py
Change default proposed config
=> Prevent unpublished events to be included in feed

pymisp/mispevent.py
Added this one, I needed, at the moment.
As discussed previously, we can see together if some other getter methods like this could be interesting
=> Method to return an object by uuid

examples/misp2clamav.py
Use from_dict() instead of set_all_values()
=> Fix misp2clamav

pymisp/api.py
Seems like a copy-pasta error. ;-)
=> Point to right anchor for client side certificates

examples/search_attributes_yara.py
Simple way of getting all attributes (of a given type) from all event you have access to.
=> Example of specifying special attribute type in your search: here yara attribute

pymisp/api.py
Hi everyone.
I've just found myself in the need of an easy API to change the Analysis status of an existing event.
In example, change "Ongoing" status to "Completed".
So, I took "change_threat_level" API as example and I created "change_analysis_status".
For any questions, I'm available. Thank you in advance
=> added change_analysis_status API

docs/tutorial/PyMISP_tutorial.ipynb, docs/tutorial/install_notebook.sh
Jupyer notebook showing the basics of PyMISP
=> Jupyter notebook

pymisp/api.py
Added the ability to add a email-header attribute type.
=> chg: Added email-header attribute

pymisp/api.py
Can fix #270
* `PyMISP.download_samples()` returns `(True, [event_id, md5, sample_bytes])` whenever it has a hash to uniquely identify the returned sample. 
* For the legacy format it continues to return `(True, [event_id, filename, sample_bytes])` 
* For zipped samples it continues to return `(True, [event_id, filename.zip, sample_bytes])`
=> Fix #270 uniquely identifying sample

pymisp/api.py
Added the following methods:
- Get Tag (by id)
- Edit Tag
- Edit Tag (via json file)
- Enable/Disable Tag (to hide or show it)
- Enable/Disable Taxonomy
- Get Taxonomy Tags List
- Enable/Disable all the Taxonomy Tags
- Enable/Disable WarningList
- Get NoticeLists
- Get NoticeList (by id)
- Enable/Disable NoticeList 
I hope everything is working properly. I tested all the methods, although some responses might not be the best.
=> add: some getters and setters for specific attributes

examples/search_sighting.py, pymisp/api.py, pymisp/aping.py, tests/testlive_comprehensive.py
To merge only when MISP/MISP#3789 has been merged
=> Sightings REST API

pymisp/api.py
Add includeProposals param to the search method
=> chg: Include proposals in attributes search

docs/tutorial/PyMISP_tutorial.ipynb
Extract the "response" field from the json result returned by misp.search_index
=> Update pymisp tutorial

pymisp/api.py
Added function to check if IOC are in warninglist.
=> Check if IOC values are in warninglist

pymisp/api.py
Added required attribute "returnFormat" and set do default value "json"
Fixed query URL also
=> Search function fix to comply new version of MISP

pymisp/tools/reportlab_generator.py, tests/reportlab_testfiles/sighting_1.json, tests/reportlab_testfiles/sighting_2.json, tests/test_reportlab.py
To be also modified in misp-modules.
**Only for verification for now**
=> Facultative text description, Sightings, Tests cases

pymisp/api.py
To allow tools to set a custom user-agent
=> new: Allow custom user-agent

examples/fetch_warninglist_hits.py, pymisp/api.py
See related MISP commits from iglocska: 6150d9e and 5c93320.
=> Added includeWarninglistHits as a possible filter for the restsearch

examples/sync_sighting.py
Sync sightings between MISP servers
Sync from multiple clients to one authoritative MISP instance.
To be run from cron
(blog docu coming)
=> Sync sightings between MISP servers

examples/edit_organisation.py, examples/edit_organisation_json.py
=> new: [example] Added edit_organisation examples.

pymisp/api.py, pymisp/mispevent.py
Basic ability to add a sharing group with the specified name, releasability, description, also allowing to set the active and property.
=> Introduce ability to create a sharing group

examples/stats_report.py
PyMISP script to run every x-days to get an overview of new
events/attributes ; MISP-Galaxies ; MITRE ; Tags
Output of report is on screen or sent via e-mail ; all stats attached
as CSV
=> Create statistical reports for MISP

pymisp/aping.py
=> Bug in _make_timestamp

pymisp/data/describeTypes.json
Based on [#4947](https://github.com/MISP/MISP/pull/4947)
=> add: New attribute type weakness

examples/stats_report.py
Next to inline configuration; allow to supply mail options as an argument via command line
=> Allow to supply mail options as arguments on command line

pymisp/aping.py
Requires https://github.com/MISP/MISP/pull/5215 to be merged first.
=> Adds support to add local tags.

pymisp/data/describeTypes.json
now using the gen_misp_types_categories using jq
So in the future, if everyone uses the script the git diff should be clean every time now.
=> chg: [types] updated to the latest version

travis/install_travis.sh, travis/test_travis.sh
Fix travis-ci failures after merging https://github.com/MISP/PyMISP/pull/473/commits/5cfe7e6b599ee460121443bc8a6ec72c379e918a via #473.
=> Follow up to PR #473

examples/feed-generator/generate.py
Allow for defining in the settings.py file the number of entries to output
=> Update generate.py - define the number of entries to output

examples/feed-generator/settings.default.py
Allow for defining in the settings.py file the number of entries to output
=> Define the number of entries to output

examples/keys.py.sample, examples/proofpoint_tap.py
custom integration written in python to scrape Proofpoint TAP API for messages blocked/delivered and clicks blocked/permitted and create MISP events
=> Proofpoint tap integration

examples/proofpoint_vap.py
custom integration written in python to scrape Proofpoint VAP API for metrics of top Very Attacked Persons and create MISP events
=> Proofpoint VAP integration

examples/trustar.conf, examples/trustar_misp.py
Custom integration to scrape Trustar Intel Platform reports and create events in MISP
=> Trustar integration

pymisp/aping.py
Added decay score bool to rest search.
=> new: add includeDecayScore to rest search

pymisp/api.py, tests/testlive_comprehensive.py
new: [dev] add extended misp event flag to `get_event()`
new: [dev] add extend event as `extend_event()`
=> new: [dev] add extended misp event

pymisp/tools/microblogobject.py
Add a microblog object generator.
=> new: [dev] add microblog object tool

tests/testlive_comprehensive.py
Test for https://github.com/MISP/MISP/issues/6145
=> chg: New test_get_non_exists_event

tests/testlive_comprehensive.py
Should be merged as soon as https://github.com/MISP/MISP/pull/6151 is merged
=> Updated generic tagging method to match incoming changes in MISP

pymisp/tools/peobject.py
This should solve the issues described in #614  
Note: I have not tested this code yet as my MISP instance is on another system and I'm not quite sure of the process of updating a python package based on a git clone.
=> Exclude section correlation .rsrc and zero-filled

pymisp/tools/emailobject.py
.eml files downloaded from Windows Online security systems on some Windows 11 OS's are automatically encoded in UTF with a byte order mark (BOM) at the front of the file. This will cause the email parser to fail.
This is a somewhat isolated problem. It only will affects a small subset of Windows users who download and re-upload eml files. But, this small subset of users is the target user-base for the MISP email module: low expertise users who wish to quickly share high-value indicators on an ad-hoc basis. (I had this issue flagged for me by one such user.)
While this fix could be tacked onto the MISP email module instead of here, I beleive that this fix is more appropriate in the PyMISP object code. As the "email" object parser this object should be built to parse all manner of emails …
=> Attempt to decode utf-8-sig encoded emails.

examples/feed-generator-from-redis/README.md
=> fix PyMISP repo URL

pymisp/api.py
Keep connection alive between requests, so PyMISP can reuse existing connection (no need to establish new encrypted channel, bigger TCP window etc.), so sending multiple requests should be much faster.
=> chg: Keep connection alive between requests

pymisp/api.py
=> update upload_stix api to send data directly

pymisp/api.py
To reduce tranfered data and speed up compression and decompressing in compared with gzip.
=> new: Support brotli compression

pymisp/mispevent.py, tests/test_mispevent.py
=> chg: Do not load schema for event when not necessary

pymisp/api.py
Will make sense after https://github.com/MISP/MISP/pull/7525 is merged.
=> new: Save one REST call when initialize PyMISP class

pymisp/mispevent.py
This PR fixes a bug in the datamodel of PyMISP in regards to SharingGroupOrgs
This fix is needed to support Sharing Groups in the Feeds . See also https://github.com/MISP/MISP/issues/5758
=> fix: [sharinggroups] Fixes wrong model for SharingGroupOrg

pymisp/tools/_psl_faup.py, pymisp/tools/urlobject.py, pyproject.toml
- Option to include more URLObject attributes
- Add publicsuffixlist faup for URLObject Windows support
- URLObject with PSLFaup prefers IP to host/domain
=> Broader URL Object Support

pymisp/__init__.py, pymisp/exceptions.py, pymisp/mispevent.py, tests/mispevent_testfiles/galaxy.json, tests/test_mispevent.py
Superset of https://github.com/MISP/PyMISP/pull/887
=> Chrisr3d galaxy features

pymisp/api.py, tests/testlive_comprehensive.py
Related to https://github.com/MISP/MISP/pull/8980
=> [new]: support breakOnDuplicate option for attributes:add()

README.md, pymisp/api.py, tests/testlive_comprehensive.py
Changes:
- Add 'event_tags' parameter when searching for events
- Add new method to search for galaxies by value
- Add new parameter to fetch cluster information when retrieving galaxies
- Add new parameter to hard-delete object references
=> Allow search by 'event_tags' and improve handling of galaxies

pymisp/api.py
Update to adapt to change here: https://github.com/MISP/MISP/commit/d629922a7fe8311e3e5be104f30a800911987e48
=> chg: allow orgc context for search_galaxy_clusters
