pymisp/api.py

I add a method in API to export attribute by type in using 'attributes/txt/download'

add method to export txt all attributes by type

---

pymisp/api.py

Tested, download_samples() is working now:
```python
misp = pymisp.PyMISP(url, key, ssl=False)
file = misp.download_samples(event_id='1234', all_samples=False)
filename = file[1][0][1]
raw = file[1][0][2]
wrapped = io.TextIOWrapper(raw)
with open(filename, 'w') as afile:
afile.write(wrapped.read())
```

Fixes: expected bytes, got <class 'str'> in download_samples()

---

pymisp/mispevent.py
tests/search_index_result.json
tests/test_offline.py

Nothing functional, just adding a test for search_index, since it was failing in 2.4.50.
While writing the test I realised it was fixed in 2.5.54.
Also, wrapping open() operations in "with" constructs to prevent "file open" warnings while running tests.

Added test for search_index and solved warnings

---

pymisp/api.py

Support the additional flags allowed in the /attributes/text/download/ links.
Also includes support for the addition from https://github.com/MISP/MISP/pull/1886

get_all_attributes_txt - support the additional flags

---

examples/yara_dump.py

This dumper also does YARA rule validation, ignores invalid rules and prevents duplicate rule names. The output is a file called misp.yara which can be used with your favorite YARA tool.

YARA dumper for all rules

---

pymisp/api.py

Throw exception instead if an invalid uuid is given to tag() and untag().
I hope i did it the right way.

throw exception for invalid uuid

---

pymisp/api.py

Using the facilities introduced by MISP commit bdbd0920ba760a514cffdb30cc741b61b589d9da
(fix: attachTagToObject and removeTagFromObject now accept posted JSON objects)
This needs MISP PR 2033 to work.

Using the facilities introduced by MISP commit ... 

---

pymisp/mispevent.py

On Windows 7 datetime.datetime.fromtimestamp(int(0)) returns a date before 1970, which causes the script to crash. This fixes the bug.

publish_timestamp Windows 7 Fix

---

examples/last.py

Output was not usable with cli utilities such as: ```cat results.json | python -m simplejson.tool```. 
It's now usable and works perfectly.

Updated last.py to dump json results straight away

---

examples/last.py
examples/search.py
examples/searchall.py

Similar to https://github.com/MISP/PyMISP/pull/68, I removed the use of '\n' since it breaks loading JSON with third-party tools afterwards.
Output was not usable with cli utilities such as: 
```bash
cat results.json | python -m simplejson.tool
```
It's now usable and works perfectly.

Fixed the JSON output format (\n breaks JSON loading afterwards)

---

pymisp/api.py

Using print in a library is not really recommended so I changed it to logging instead.
The debug option of PyMISP is now deprecated and using it triggers a warning, instead configure logging as you please.

Use logging instead of print; deprecate debug param

---

pymisp/api.py

The previous version check might give incorrect results because a string comparison is used. E.g. '2.0.10' < '2.0.2'

Fix checks of recommended version

---

pymisp/api.py

resolve 87
check for not_values type instead of values when preparing rest query parameters in search API calls
method __prepare_rest_search
@Rafiot  please check it out
thank you

Fix not_values type check in __prepare_rest_search issue #87

---

.travis.yml
setup.py
tests/test_offline.py

This does not fix #110, it only affects the tests.

Tests: skip optional ones and update requirement

---

pymisp/mispevent.py

When a user tries to add an object with a name that doesn't exist, the error thrown was missing its format string
This ended up looking like:
```
pymisp.exceptions.UnknownMISPObjectTemplate: {} is unknown in the MISP object directory.
```
Here's a patch that adds self.name to the format string

Formatted "Unknown MISP object" error message

---

pymisp/mispevent.py

`add_attribute_tag(tag,attribute_identifier)` fails if attribute does not have any tag in before.
Side note: It would be better if the creation of tags at attribute level would be possible even before the first saving of the event. It would be easily possible by change the if statement `if (a.id == attribute_identifier or a.uuid == attribute_identifier or
attribute_identifier == a.value or attribute_identifier in a.value.split('|')):` in a way that it does not fail in case of non-existent db attributes (`uuid,id`)

Similar to #114 on attribute level

---

pymisp/api.py

Added change so I could pass additional params to the the add_attachment. In my case it was "disable_correlation=True". It never actually made it down to the add_named_attribute b/c it was misssing **kwargs.

Added **kwargs to add_named_attribute call in add_attachment

---

README.md
pymisp/api.py

- Updated 2 bad indentations where epydoc was Warning

Remove CIRCL repo references from README.md & fix epydoc

---

pymisp/api.py

Further details can be found in the commit messages.
I aim to next look at what the server is doing with my request that it sometimes generates a 500 response with an internal error message, but most often generates a 500 response with no content.

Check explicitly for a 500 response from the server with no response content

---

pymisp/api.py

'last' gives the latest events that have been published
- add get_events_last_modified()
this function returns the modified events based on timestamp
how to use : 
```python
r = misp.get_events_last_modified(search_from="2017-11-28")
for a in r['response']:
print(a['Event']['id'])
```
dates are converted to timestamp

Correction for 'last' param and add function who get last modified

---

README.md

Adds a missing element that might frustrate other people...

document submodule downloading

---

tests/test.py

This commit change the `add_hashes` function call in the test.py file to follow the correct parameters naming, according to the comment made by @Rafiot in #174.
However, this function tests seems to never be called at all during either the Travis build nor a manual call of the script, so maybe adding an example script would be a better idea?
Thanks!

Fix add_hashes online test function parameters

---

pymisp/mispevent.py

As of now add_attribute_tag only searches for plain attributes. With this commit attributes within objects are searched as well.

add attributes within objects as well, for tagging via value/id/uuid

---

pymisp/api.py

added the possibility to search sightings : 
Here some example : 
```python
print(misp.sighting_list(424242))
```
The answer will give a sighting list corresponding to the attribute 424242.
```python
print(misp.sighting_list(element_id=42, org_id=2, scope=event))
```
The return will be a sighting list of event 42 with a filter for organisation 2.

add search on sighting

---

examples/misp2cef.py

A way to export all to_ids attributes in CEF format. Adopted from https://github.com/MISP/misp-modules/blob/master/misp_modules/modules/export_mod/cef_export.py by Hannah Ward.

Add misp2cef example

---

pymisp/abstract.py

Doing the following raise an exception:
```
json = '''{
"type": "ip-src",
"value": "8.8.8.8",
"category": "Network activity",
"to_ids": false,
"proposal": false
}'''
attribute = MISPAttribute()
attribute.from_json(json)
```
TypeError: from_dict() takes 1 positional argument but 2 were given

fix: AbstractMISP.from_dict() do not accept positional argument

---

pymisp/data/describeTypes.json

As described in https://github.com/MISP/MISP/pull/3119, `External analysis` is not that good as a default category from my point of view. To complete the change of default category type it has to be changed in `pymisp/data/describeTypes.json`, too.

Update default category for url

---

pymisp/api.py

**Use case**: Many sandboxes accept the passworded sample. We don't want to unzip it.
There is no change for existing scripts, so this should be fine?
Thanks!

Added download_samples(..., unzip=True)

---

examples/add_named_attribute.py
examples/add_user.py
examples/add_user_json.py
examples/create_events.py
examples/delete_user.py
examples/edit_user.py
examples/edit_user_json.py
examples/et2misp.py
examples/fetch_events_feed.py
examples/freetext.py
examples/misp2cef.py
examples/misp2clamav.py
examples/sharing_groups.py
examples/sighting.py
examples/suricata.py
examples/tags.py
examples/up.py
examples/users_list.py
examples/warninglists.py

part of examples scripts had True value whereas there is a custom setting for certificate validation used in others.
required for automated pipeline testing with self-signed certificate.

align examples on custom usage of misp_verifycert

---

pymisp/api.py

Possibility to fetch users/statistics data for all context (usage, org, tags, ...)

new: [usersStats] Possibility to fetch users/statistics

---

pymisp/api.py
tests/test_offline.py

Add new function `PyMISP.change_disablecorrelation(attribute_uuid,disable_correlation)` to be able to enable/disable correlation on attributes.
The goal is to be able to enable or disable correlation on single attribute as you can do with ids flag.

Add new function PyMISP.change_disablecorrelation()

---

pymisp/api.py

the fix for #365 gave an error:
'NoneType' object has no attribute 'setdefault'
This small patch should fix that :)

fix for "'NoneType' object has no attribute 'setdefault'"

---

examples/vmray_automation.py

Import finished VMRay tasks ; add attributes to event
Makes use of the 'incomplete' workflow taxonomy
Needs to be put in a cronjob to run in the background
Only works with the new vmray modules (submit/import)

Automation script that links vmray_submit and vmray_import

---

pymisp/api.py
pymisp/aping.py

PyMISP always expects the response to be of JSON type. However, if you specify the ``returnFormat`` in MISP to be, for example, ``csv``, PyMISP will throw an error.
If you see a cleaner way to solve that issue, please say so :)

fix: [direct_call] Allows the response type to be something else than a JSON (e.g. csv)

---

pymisp/tools/openioc.py

The commits allow the use of
- `RouteEntryItem/Destination/IP`
- `RouteEntryItem/Destination/string`
as they are given in the mapping, but never used. I explicitly check for `RouteEntryItem/Destination` in the Context > search xml attribute, because there might be some side effects if implemented in a more generic way.  
Also, the default mapping for `RouteEntryItem/Destination/string` has been changed to `hostname` instead of `url`. This makes sense to me, because a URL includes a scheme usually and at this point of the mapping there would otherwise be a distinction between `IP` ("schemeless") and `url` (scheme required).

[OpenIOC] Allow the use of content type for RouteEntryItem/Destination

---

examples/search_sighting.py

This example called an undefined function and therefor did not work.
Fix for https://github.com/MISP/PyMISP/issues/420

Fix for issue 420

---

pymisp/aping.py

Fixes: #429
Same request as in the issue now produces:
```
GET /servers/getPyMISPVersion.json HTTP/1.1
Host: localhost:1337
User-Agent: PyMISP 2.4.111.2 - Python 3.7
Accept-Encoding: gzip, deflate
Accept: application/json
Connection: keep-alive
Authorization: asdf
content-type: application/json
```

Fix missing f in f-string

---

pymisp/tools/create_misp_object.py

In all cases but one, the 3rd returned object is a (potentially empty) list.

chg: Return empty list instead of None

---

examples/stats_report.py

The `stats_report.py` example relied on deprecated functions making it crash.
This has been fixed by upgrading to `ExpandedPyMISP`. Further checks have
been introduced to ensure used dictionary keys do exist as the example
also crashed on clean MISP instances due to empty responses.

Fix stats_report example to use ExpandedPyMISP

---

.gitignore

Exclude the following files from git:
- .coverage
- tests/reportlab_testoutputs/*.pdf

Update .gitignore to exclude files produced during tests

---

.gitmodules

Since the files are required for the tests anyway, I think it makes sense to have them as a Git submodule, just like the MISP object definitions.

Add viper-test-files repository as Git submodule

---

pymisp/api.py

We aren't actually using MISPFileCache._load_json in PyMISP or ExpandedPyMISP.

Remove unused MISPFileCache from PyMISP class

---

pymisp/aping.py

I just stumbled over the keyword args of the PyMISPExpanded.search method. The documentation said that there is a kwarg __returnFormat__ but it really is __return_format__
https://pymisp.readthedocs.io/modules.html#pymisp.ExpandedPyMISP.search
So I fixed it, if you want here is a PR...
Thanks for your good work, keep it up!
Shorti

Corrected docstring

---

pymisp/mispevent.py
tests/testlive_comprehensive.py

- check for timezone sign after the date field
- updated ``*-seen`` test to avoid errors while testing using python 3.6 (do not support tz=08:00 but do support 0800)

Tweaking on datetime parsing

---

pymisp/tools/vtreportobject.py

__query_virustotal returned a Response object and not the json expected; modified so that report_json is returned instead of report.

Fixed __query_virustotal return type

---

pymisp/abstract.py

Make PyMISP opens files in utf-8 and not the system default

fix: [abstract] Forces file to be read with utf8 encoding

---

pymisp/api.py

* remove typo in ssl parameter docstring. 
* Add hint that other certs (which are not in the default CAs, but also are not self signed in a strict sense) can also use the CA_BUNDLE function of the ssl parameter.

Update docstring in api.py

---

pymisp/api.py

This fixes feature request #528 
In my own tests all went well, let's see what the automated tests say.

new: Timeout for connection/request, fixes #584

---

pymisp/tools/fileobject.py
tests/test_fileobject.py

instead of the mimetype. According to [MISP DataModels](https://www.misp-project.org/datamodels/#types)
```
mime-type: A media type (also MIME type and content type) is a two-part identifier for file formats and format contents transmitted on the Internet
```
more precisely defined in [RFC2045](https://tools.ietf.org/html/rfc2045) and others.
The description returned by libmagic is more useful than the generic mime-type,
but I did not find a place to put the description in the current data model.

Previously file object was reporting the libmagic description of a file

---

pymisp/abstract.py
pymisp/api.py
pymisp/mispevent.py
pymisp/tools/asnobject.py
pymisp/tools/domainipobject.py
pymisp/tools/elfobject.py
pymisp/tools/emailobject.py
pymisp/tools/fail2banobject.py
pymisp/tools/fileobject.py
pymisp/tools/geolocationobject.py
pymisp/tools/git_vuln_finder_object.py
pymisp/tools/machoobject.py
pymisp/tools/microblogobject.py
pymisp/tools/peobject.py
pymisp/tools/sbsignatureobject.py
pymisp/tools/sshauthkeyobject.py
pymisp/tools/urlobject.py
pymisp/tools/vehicleobject.py
pymisp/tools/vtreportobject.py
tests/test_mispevent.py

- MISPObject is now standalone by defaults, and add_object, update_object and get_object set standalone to False.
- MISPObject.standalone is a property. Setting it uses AbstractMISP._remove_from_not_jsonable or update_not_jsonable.
- Classes inheriting MISPObject don't have to change standalone default value to True anymore

Issue 593 change standalone policy

---

pymisp/api.py

I'm not sure why the `print_exc` was added in the first place, but it make sure you can't silently catch the exception. I believe it should be removed.
E.g. this would produce a full trace:
```python
import pymisp
try:
pymisp.ExpandedPyMISP("http://localhost", "asdf")
except:
pass
```

Remove explicit traceback printing

---

pymisp/api.py

There shouldn't be any need to check the loglevel before logging the same level. The logger itself will handle this.

Remove explicit loglevel checking

---

pymisp/api.py

This check is not necessary, because `logger.debug` method is defined as:
```python
def debug(self, msg, *args, **kwargs):
"""
Log 'msg % args' with severity 'DEBUG'.
To pass exception information, use the keyword argument exc_info with
a true value, e.g.
logger.debug("Houston, we have a %s", "thorny problem", exc_info=1)
"""
if self.isEnabledFor(DEBUG):
self._log(DEBUG, msg, args, **kwargs)
```

fix: Remove duplicate check if debug logging is enabled

---

pymisp/abstract.py

json.load() doesn't have encoding= in Python 3.9. Proposed fix.

Drop `encoding=` in Python 3.9

---

pymisp/mispevent.py

Add ":param " prefix to parameters to improve ReadTheDocs output.
Fix some minor typos in docstrings.

chg: format docstrings in mispevent.py

---

pymisp/tools/emailobject.py

Ran into an email sent through gmail, where one "received" header line didn't have a "from" field, adding simple check to prevent a hard failure

adding check if "from" is in the "received" header row

---

pymisp/__init__.py
pymisp/api.py
pymisp/exceptions.py
pymisp/mispevent.py
tests/testlive_comprehensive.py

Now we have Event Reports in MISP, thought it would be a good thing to be able to manage this through PyMISP.
Unfortunately with the current MISP codebase, there are a few limitations:
- The 'hard' delete flag must be passed in the url as `/1` and not as a POSTed JSON.
- This must be managed through the PyMISP func, e.g. `pm.add_event_report` and not through the `MISPEvent` class. MISP doesn't seem to recognise changes to `EventReports` and update accordingly when POSTed in the Event JSON. As such, I have not included a setter prop for the `MISPEvent.event_reports property.`
Does what we're looking for though :)

new: Add in ability to create/update/delete MISP Event Reports

---

pymisp/mispevent.py

Noticed that the MISPObject class didn't have a 'delete' function like a MISPAttribute did, this fixes that. Tested on MISP v2.4.137 and successfully soft deletes an object

Add in delete function for a MISP Object

---

examples/keys.py.sample
examples/proofpoint_tap.py

The Proofpoint TAP example was broken.
- The auth to Proofpoint was not using built-in HTTP Basic Auth, and instead was doing it manually in the header
- The org being set was unnecessary as it uses the misp_key's org as the creator org
- Added error-checking for leaving auth tokens blank
- Ignore SSL verification warnings

Fixed Proofpoint TAP Example

---

pymisp/abstract.py
pymisp/mispevent.py
tests/test_mispevent.py

This call replaces calling `json.loads(misp_event.to_json())` that is super inefficient.

new: `to_dict` method supports `json_format` parameter

---

pymisp/tools/emailobject.py

Fix #787
- Uses regex to pick up the hostnames/domains from the "Received: from" headers.
Unicode to ASCII function
- Spam messages more often than not contain junk text as unicode characters in the headers. The "from" and "subject" headers being the most common ones. Before this change the script would error on such emails or sometimes replace the unicode characters with questionmarks "?".
- Function takes argument as an input and then encodes it in ascii while ignoring any malformed data. It then returns an ASCII string without the unicode characters.
- Currently implemented for "from" and "subject" handling.

Fix #787 and add Unicode to ASCII function

---

examples/feed-generator/generate.py
examples/feed-generator/settings.default.py

- Revert back the event initial search to use the index endpoint instead of RestSearch
- Relying on RestSearch was offering more flexibility than index in terms of filtering options, however, it might introduce a significant overhead potentially leading to timeout for some server.
- Add a means to filter out specified attribute types

Feature feedgenerator exclude malwares

---

examples/feed-generator/generate.py
examples/feed-generator/settings.default.py
pymisp/mispevent.py

This PR brings in the option to export the feed with distribution and Sharing Group information.
This is one of the requirements to fully support distribution/sharing groups in the Feed system, see https://github.com/MISP/MISP/issues/5758

chg: [feed-generator] support for distribution and sharing groups

---

examples/feed-generator/generate.py
examples/feed-generator/settings.default.py
pymisp/abstract.py
pymisp/mispevent.py

This adds the parameter `with_local_tags` to the MISPEvent `to_feed()` function, which allows you to exclude your local tags from the feed export.  Since I'll be sharing the feed, local tags is not something I want to include.  However, I did set the default to `True`, since that is the current behavior.
Code includes an update to the `feed-generator` example.

Add feed option for local tag exclusion

---

pymisp/api.py
tests/testlive_comprehensive.py

I recently introduced the ability to search by sharing group on the rest search 'events' or 'attributes' controller as per https://github.com/MISP/MISP/pull/8277. Released as part of v2.4.158
This brings the functionality into PyMISP, and yes I've even remembered to do a test case :)

new: Search by sharing groups

---

pymisp/abstract.py

This allows for better deterministic feed output generation.

Ensure that keys are sorted in the returned `_to_feed()` dictionary

---

pymisp/mispevent.py

In some cases, due to historical reasons, MISP objects might not contain a `template_uuid`. 
When this happens the MISP feed exporter complains and does not export the event.
Current MISP versions require a present template uuid when importing events, so exporting an empty uuid is not an option. The proposal to address this is by using a hardcoded uuid, that is obviously non-random. Objects exported this way will therefore be correctly imported by MISP, and remain non-editable.
Note1: impact on MISP: none. A fake uuid results in objects not being editable, which would also have been the case if the uuid was absent.
Note2: a few numbers are `aaaa`, this is because cakephp refuses to accept an uuid with only `1`.

fix: [feed] fixes bug when template_uuid does not exist

---

pymisp/api.py

typo where the variable was printed instead of the actual value.

api.py: fix typo in logging message for PyMISP recommended version

---

pymisp/api.py

Many teams run pymisp clients in a way where stdout/stderr gets logged centrally long term. This can be problematic if we're logging single factor auth API keys that don't rotate. This is a small change to remove the Authorization key from the request headers dictionary before passing to the logger.

Update 500 errors to exclude logging authorization header

---

pymisp/api.py
tests/testlive_comprehensive.py

I noticed that the `search_index` function did not have the ability to sort or perform pagination. Had a quick check of MISP's API, and the endpoint already supports these parameters, so a very simple change!

Sort/desc for sorting results and limit/page for pagination

---

pymisp/api.py
tests/testlive_comprehensive.py

This PR adds in the functionality to set a taxonomies required status as per #831. Turns out the toggle isn't really a toggle on MISP's API and you in fact provide the `required` parameter in the request.
Tested locally and can confirm it appropriately sets the `required` value of the respective taxonomy

Add in ability to set a taxonomies required status

---

pymisp/api.py

Uplift to get a 405 Invalid tag response rather than getting an AttributeError exception.

Graceful handling of tagging when name attribute is missing

---

examples/add_attributes_from_csv.py

The script aims to ingest a formated CSV file containing attributes and details for quick MISP ingestion in an existing event.
The expected format is the following:
`value;category;type;comment;to_ids;first_seen;last_seen;tag1;tag2`
`test.pdf;Payload delivery;filename;Email attachment;0;1970-01-01;2022-09-02T14:52:28+0200;tlp:green;ransomware`
`127.0.0.1;Network activity;ip-dst;C2 server;1;;;tlp:white;`

Creation of script named "add_attributes_from_csv.py"

---

pymisp/mispevent.py

Add with_event_reports keyword argument allows users to specify whether or not they want to include event reports in their feed-formatted events.
with_distribution and valid_distributions parameters are honoured by this new parameter.

Add kwarg to to_feed() that allows users to include event reports

---

setup.cfg

Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead. By 2023-Sep-26, you need to update your project and remove deprecated calls or your builds will no longer be supported.
See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.

Using underscore name 'description_file' in setup.cfg

---

pymisp/mispevent.py

@Rafiot was it intended to leave the galaxy without a setter? I have a use case to assign galaxies from one event to another and I would like to have this functionality in PyMISP.

feat: Introduces a setter for galaxies

---

pymisp/api.py

Add the ability to provide a custom HTTPS adapter to the PyMISP class. With M2Crypto and m2requests, this can enable mutual TLS with hardware tokens #1118.

Add HTTPS Adapter

---

.github/workflows/pytest.yml
README.md
poetry.lock
pymisp/abstract.py
pymisp/api.py
pymisp/mispevent.py

orjson is much faster library for decoding and encoding JSON formats

Add support for orjson

---

pymisp/tools/create_misp_object.py

Commit 9853f23 erroneously moved the import of `FileObject` in `pymisp/tools/create_misp_object.py` to the `TYPE_CHECKING` conditional. This was later changed by 8fb34a2, however, the commit moved the import inside the try-except-block related to `lief`. As a consequence `FileObject` is not imported if `lief` is not available, but it is needed regardless, resulting in confusing exceptions unrelated to `lief`:
```
Traceback (most recent call last):
File "/home/user/test.py", line 16, in <module>
event.run_expansions()
File "/home/user/.venv/lib/python3.10/site-packages/pymisp/mispevent.py", line 2029, in run_expansions
file_object, bin_type_object, bin_section_objects = make_binary_objects(pseudofile=attribute.malware_binary, filename=attribute.malware_filename)
File …
```

fix: Correct FileObject import

---

pymisp/api.py
tests/testlive_comprehensive.py

This pull request resolves the issue https://github.com/MISP/PyMISP/issues/975 with a new method to attach a galaxy cluster to an Event or an Attribute, without using the connector tags.

Add attach galaxy cluster method

---

pymisp/exceptions.py
pymisp/mispevent.py

Use case: To diff two instances of the same event.
Similar to `get_object_by_id` and `get_object_by_uuid` methods, implemented `get_attribute_by_id` and `get_attribute_by_uuid` to find an attribute in an event or object using attribute id or UUID.

feat: Adds methods to get attribute by id/uuid

---

pymisp/api.py

This change simply adds two methods to add and update (existing) MISP roles, similar to existing `add_X` and `update_X` methods.

feat: Adds methods to add and update MISP roles

---

examples/feed-generator/generate.py
examples/feed-generator/settings.default.py
pymisp/mispevent.py

- added new class CryptographicKeys
- added functions to to_feed calls to include crypto keys
- added protected boolean field to misp event
- updated feed generator to support signing
- if the new setting is set to True signing will be attempted for protected events
- protected events are now passed to the /cryptographic_keys/serverSign endpoint of misp for signing
- signatures are included as a .asc file in the output directory
- TODO:
- currently the JSON dumping is moved from a streamed dumping to an in memory dump before saving to disk
- add a check for protected events and revert to streamed dumping for non protected events
- alternatively use the already saved files to request signing from MISP

new: [support for signing] added

---

pymisp/tools/emailobject.py

- Rewrite of the section that deals with the logic handling the Received headers
- Previous version was not picking picking up e.g. Reverse DNS hostnames at all and some of the IPs were not ever handled
- Fixes #1321

fix: [emailobject] Improve parsing of the Received headers

---

pymisp/mispevent.py

At the moment, the signature of the method allows the passing of an unpacked list that is empty and the loop is simply skipped with no feedback.
To make the behaviour more aligned to the [add_attribute](https://github.com/MISP/PyMISP/blob/b0632cca12f8f75e7af22d84591163f69f7b1579/pymisp/mispevent.py#L1083) method, I would suggest adding a check and an informative warning in the case this happens.

Add a check if MISPObject.add_attributes() method has truly values to add
